# Generated by Django 4.0.2 on 2023-01-08 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Имя',
        ),
    ]
