# Generated by Django 4.0.2 on 2023-01-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_is_admin_customuser_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='image',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Имя',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Отчество',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Фамилия',
        ),
        migrations.AddField(
            model_name='teacher',
            name='job_title',
            field=models.CharField(default=3, max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject_id',
            field=models.CharField(default=3, max_length=5),
            preserve_default=False,
        ),
    ]
