# Generated by Django 4.0.2 on 2022-03-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='for_whom',
            field=models.CharField(choices=[('Мугалимдер үчүн', 'Мугалимдер үчүн'), ('Окуучулар үчүн', 'Окуучулар үчүн'), ('Ата-энелер үчүн', 'Ата-энелер үчүн')], default='Окуучулар үчүн', max_length=20, verbose_name='Кимдер үчүн'),
        ),
    ]
