# Generated by Django 4.0.2 on 2022-02-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Мектеп жөнүндө маалыматтын темасы')),
                ('image', models.ImageField(upload_to='', verbose_name='Сүрөт жүктөө')),
                ('description', models.TextField(verbose_name='Мектеп жөнүндө маалымат')),
            ],
        ),
    ]
