# Generated by Django 4.0.2 on 2022-03-02 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainAboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Мектеп жөнүндө маалыматтын темасы')),
                ('description', models.TextField(verbose_name='Мектеп жөнүндө маалымат')),
            ],
            options={
                'verbose_name': 'Башкы баракча маалыматы',
                'verbose_name_plural': 'Башкы баракча маалыматтары',
                'db_table': 'about_us',
            },
        ),
        migrations.CreateModel(
            name='AboutUsFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='media/files/%Y/%m', verbose_name='Файл жүктөө')),
                ('about_us', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aboutUs.mainaboutus')),
            ],
            options={
                'db_table': 'files',
            },
        ),
    ]
