# Generated by Django 4.0.2 on 2022-02-21 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainaboutus',
            options={'verbose_name': 'Башкы баракча маалыматы', 'verbose_name_plural': 'Башкы баракча маалыматтары'},
        ),
        migrations.AlterModelTable(
            name='mainaboutus',
            table='about_us',
        ),
    ]
