# Generated by Django 4.0.2 on 2022-03-02 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusfiles',
            name='title',
            field=models.CharField(default=21312, max_length=255, verbose_name='Файл жөнүндө маалымат'),
            preserve_default=False,
        ),
    ]
