# Generated by Django 4.0.2 on 2022-02-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0002_alter_mainaboutus_options_alter_mainaboutus_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainaboutus',
            name='image',
            field=models.ImageField(upload_to='images/%Y/%m', verbose_name='Сүрөт жүктөө'),
        ),
    ]
