# Generated by Django 4.0.2 on 2022-03-02 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0002_aboutusfiles_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusfiles',
            name='about_us',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_us_files', to='aboutUs.mainaboutus'),
        ),
    ]
