# Generated by Django 4.0.2 on 2022-03-02 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0003_alter_aboutusfiles_about_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusfiles',
            name='file',
            field=models.FileField(null=True, upload_to='files/%Y/%m', verbose_name='Файл жүктөө'),
        ),
    ]
