# Generated by Django 4.0.2 on 2022-03-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0004_alter_aboutusfiles_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Аты-жөнү')),
                ('position', models.CharField(max_length=50, verbose_name='Позициясы')),
                ('lesson', models.CharField(max_length=50, verbose_name='Сабак')),
                ('timetable', models.TextField(verbose_name='График')),
                ('progress', models.TextField(verbose_name='Жетишкендиктери')),
                ('contacts', models.CharField(max_length=255, verbose_name='Байланышуу')),
                ('avatar', models.ImageField(upload_to='avatars')),
            ],
            options={
                'verbose_name': 'Мугалим',
                'verbose_name_plural': 'Мугалимдер',
                'db_table': 'teachers',
            },
        ),
        migrations.AlterModelOptions(
            name='aboutusfiles',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлдар'},
        ),
    ]
