# Generated by Django 4.0.2 on 2022-03-12 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0007_schooladmission_schooladmissionfiles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='schooladmissionfiles',
            name='school_admin_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='aboutUs.schooladmission'),
            preserve_default=False,
        ),
    ]
