# Generated by Django 4.0.2 on 2022-03-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GloryBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Аты-жөнү')),
                ('class_no', models.CharField(max_length=10, verbose_name='Классы')),
                ('avatar', models.ImageField(upload_to='avatars', verbose_name='Сүрөтүн жүктөө')),
                ('glory_whom', models.CharField(choices=[('Мугалим', 'Мугалим'), ('Окуучу', 'Окуучу')], default='Окуучу', max_length=20, verbose_name='Сыйлануучу')),
            ],
            options={
                'verbose_name': 'Сыйлануучу',
                'verbose_name_plural': 'Ардак тактасы',
                'db_table': 'glory_board',
            },
        ),
        migrations.AlterField(
            model_name='teachers',
            name='avatar',
            field=models.ImageField(upload_to='avatars', verbose_name='Сүрөтүн жүктөө'),
        ),
    ]
