# Generated by Django 4.0.2 on 2022-03-04 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0002_gloryboard_alter_teachers_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gloryboard',
            name='class_no',
            field=models.CharField(max_length=10, null=True, verbose_name='Классы'),
        ),
    ]
