# Generated by Django 4.0.2 on 2022-03-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutUs', '0004_alter_gloryboard_class_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gloryboard',
            name='class_no',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Классы'),
        ),
    ]
