# Generated by Django 4.0.2 on 2022-03-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsfiles',
            name='title',
            field=models.CharField(default=123, max_length=255, verbose_name='Файл жөнүндө маалымат'),
            preserve_default=False,
        ),
    ]
