# Generated by Django 4.0.2 on 2022-03-10 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_notification_for_whom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='for_whom',
        ),
        migrations.CreateModel(
            name='ForWhom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('human', models.CharField(max_length=50, verbose_name='Ким үчүн')),
                ('for_whom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.notification', verbose_name='Кимдер үчүн')),
            ],
            options={
                'verbose_name': 'Кулактандырууну алуучулар',
                'db_table': 'human',
            },
        ),
    ]
