# Generated by Django 4.0.2 on 2022-03-10 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_notification_for_whom_forwhom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forwhom',
            name='for_whom',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='news.notification', verbose_name='Кимдер үчүн'),
        ),
    ]
