# Generated by Django 4.0.2 on 2022-03-10 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_forwhom_for_whom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forwhom',
            old_name='for_whom',
            new_name='not_id',
        ),
    ]
