# Generated by Django 4.0.2 on 2022-03-12 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_rename_for_whom_forwhom_not_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='human',
            field=models.CharField(choices=[('M', 'Мугалим'), ('O', 'Окуучу'), ('P', 'Ата-эне')], default='Окуучу', max_length=50, verbose_name='Ким үчүн'),
        ),
        migrations.DeleteModel(
            name='ForWhom',
        ),
    ]
