# Generated by Django 4.0.2 on 2022-03-10 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='file',
            field=models.FileField(null=True, upload_to='files/%Y/%m', verbose_name='Файл жүктөө'),
        ),
        migrations.DeleteModel(
            name='ScheduleFiles',
        ),
    ]
