# Generated by Django 4.0.2 on 2022-03-02 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryfiles',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Сүрөт жөнүндө маалымат'),
        ),
        migrations.AlterField(
            model_name='schedulefiles',
            name='title',
            field=models.CharField(max_length=255, null=True, verbose_name='Файл жөнүндө маалымат'),
        ),
    ]
