# Generated by Django 4.0.2 on 2022-03-02 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_galleryfiles_title_alter_schedulefiles_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulefiles',
            name='about_us',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_files', to='files.schedule'),
        ),
    ]
