# Generated by Django 4.0.2 on 2022-03-02 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_schedulefiles_about_us'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleryfiles',
            name='about_us',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_files', to='files.gallery'),
        ),
        migrations.AlterField(
            model_name='schedulefiles',
            name='about_us',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_files', to='files.schedule'),
        ),
    ]
