# Generated by Django 4.0.2 on 2022-03-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_slider_sliderfiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sliderfiles',
            options={'verbose_name': 'Слайдер үчүн сүрөттөр', 'verbose_name_plural': 'Слайдерлер сүрөттөрү'},
        ),
        migrations.RemoveField(
            model_name='slider',
            name='title',
        ),
        migrations.AddField(
            model_name='sliderfiles',
            name='sub_title',
            field=models.CharField(default=3, max_length=255, verbose_name='Сүрөттүн подтемасы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sliderfiles',
            name='title',
            field=models.CharField(default=3, max_length=255, verbose_name='Сүрөттүн темасы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
