# Generated by Django 4.0.2 on 2022-03-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_sliderfiles_options_remove_slider_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='file',
            field=models.ImageField(default=3, upload_to='files/%Y/%m', verbose_name='Сүрөт жүктөө'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='sub_title',
            field=models.CharField(default=3, max_length=255, verbose_name='Сүрөттүн подтемасы'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='slider',
            name='title',
            field=models.CharField(default=3, max_length=255, verbose_name='Сүрөттүн темасы'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='slider',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='SliderFiles',
        ),
    ]
