# Generated by Django 4.0.2 on 2022-03-02 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_alter_galleryfiles_about_us_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galleryfiles',
            old_name='about_us',
            new_name='gallery_id',
        ),
        migrations.RenameField(
            model_name='schedulefiles',
            old_name='about_us',
            new_name='schedule_id',
        ),
        migrations.RemoveField(
            model_name='galleryfiles',
            name='title',
        ),
        migrations.RemoveField(
            model_name='schedulefiles',
            name='title',
        ),
    ]
