# Generated by Django 4.0.2 on 2022-03-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_slider_file_slider_sub_title_slider_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Файлдын аты')),
                ('created_at', models.DateField(auto_now=True, verbose_name='Жүктөлгөн датасы')),
            ],
            options={
                'verbose_name': 'Мектеп документи',
                'verbose_name_plural': 'Мектеп документтери',
                'db_table': 'school_docs',
            },
        ),
        migrations.CreateModel(
            name='SchoolDocumentsFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files/%Y/%m', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Мектеп документи',
                'verbose_name_plural': 'Мектеп документтери',
                'db_table': 'school_docs_files',
            },
        ),
    ]
