# Generated by Django 4.0.2 on 2022-05-28 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_schooldocumentsfiles_doc_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accreditation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Аккредитация документтери')),
                ('file', models.FileField(null=True, upload_to='files/%Y/%m', verbose_name='Файл жүктөө')),
            ],
            options={
                'verbose_name': 'Аккредитация',
                'verbose_name_plural': 'Аккредитация',
                'db_table': 'accreditation',
            },
        ),
        migrations.AlterField(
            model_name='schooldocumentsfiles',
            name='file',
            field=models.FileField(upload_to='files/%Y/%m', verbose_name='Файл жүктөө'),
        ),
    ]
