# Generated by Django 4.0.2 on 2022-05-28 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0008_accreditation_alter_schooldocumentsfiles_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditation',
            name='type',
            field=models.CharField(choices=[('Institutional', 'Институционалдык'), ('Software', 'Программалык')], default='Институционалдык', max_length=17, verbose_name='Түрү'),
        ),
    ]
