# Generated by Django 4.0.2 on 2023-01-09 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedulefiles',
            name='file_ky',
            field=models.FileField(null=True, upload_to='files/%Y/%m', verbose_name='Файл жүктөө'),
        ),
        migrations.AddField(
            model_name='schedulefiles',
            name='file_ru',
            field=models.FileField(null=True, upload_to='files/%Y/%m', verbose_name='Файл жүктөө'),
        ),
        migrations.AddField(
            model_name='schedulefiles',
            name='schedule_id_ky',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_files', to='files.schedule'),
        ),
        migrations.AddField(
            model_name='schedulefiles',
            name='schedule_id_ru',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_files', to='files.schedule'),
        ),
    ]
