# Generated by Django 3.2.9 on 2022-11-12 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slider',
            name='file',
            field=models.FileField(null=True, upload_to='files/%Y/%m', verbose_name='Сүрөт жүктөө'),
        ),
    ]
