# Generated by Django 4.0.2 on 2023-01-09 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_schedulefiles_file_ky_schedulefiles_file_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='title_ky',
            field=models.CharField(max_length=255, null=True, verbose_name='Сүрөттүн тематикасы'),
        ),
        migrations.AddField(
            model_name='gallery',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Сүрөттүн тематикасы'),
        ),
    ]
