# Generated by Django 4.0.2 on 2022-12-12 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_alter_slider_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='accreditation',
            name='file_type',
            field=models.CharField(choices=[(1, 'Программалык'), (2, 'Институтционалдык')], default=1, max_length=30, verbose_name='Документтин түрү'),
            preserve_default=False,
        ),
    ]
