# Generated by Django 4.0.2 on 2023-01-09 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_gallery_title_ky_gallery_title_ru'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='gallery',
            table=None,
        ),
    ]
